all: build 01HolaMundo 02HolaMundo 03LineaComandos 04NumerosPrimos 05PasarAMayusculas 06BuscarCaracter 07ParametroPorReferencia 08Estructura 09ArrayDeEstructuras 10PrincipalEstados
build:
	mkdir build
01HolaMundo: 01HolaMundo.c
	gcc 01HolaMundo.c -o build/01HolaMundo
02HolaMundo: 02HolaMundo.c
	gcc 02HolaMundo.c -o build/02HolaMundo
03LineaComandos: 03LineaComandos.c
	gcc 03LineaComandos.c -o build/03LineaComandos
04NumerosPrimos: 04NumerosPrimos.c
	gcc 04NumerosPrimos.c -o build/04NumerosPrimos
05PasarAMayusculas: 05PasarAMayusculas.c
	gcc 05PasarAMayusculas.c -o build/05PasarAMayusculas
06BuscarCaracter: 06BuscarCaracter.c
	gcc 06BuscarCaracter.c -o build/06BuscarCaracter
07ParametroPorReferencia: 07ParametroPorReferencia.c
	gcc 07ParametroPorReferencia.c -o build/07ParametroPorReferencia
08Estructura: 08Estructura.c
	gcc 08Estructura.c -o build/08Estructura
09ArrayDeEstructuras: 09ArrayDeEstructuras.c
	gcc 09ArrayDeEstructuras.c -o build/09ArrayDeEstructuras
10PrincipalEstados: 10PrincipalEstados.c 10Estados.c
	gcc 10PrincipalEstados.c 10Estados.c -o build/10PrincipalEstados
